name: Cypress Test
'on': push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Cypress run
        uses: cypress-io/github-action@v5
      - name: Merge test results into one
        run: npm run report:merge
      - name: Generate HTML report
        run: npm run report:generate
         
          
